services:
  # Backend Node.js
  - type: web
    name: center-backend-nodejs
    env: docker
    dockerfilePath: ./Dockerfile.node
    dockerContext: ./backend
    region: oregon
    plan: free
    branch: main
    healthCheckPath: /api/server-info
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_SECRET_KEY
        generateValue: true
    autoDeploy: true
